[[language]]
name = "markdown"
language-server = { command = "ltex-ls" }
config = { ltex = { language = "en-GB" } }
file-types = ["md"]
scope = "source.markdown"
roots = []
formatter = { command = 'prettier', args = ["--parser", "markdown"] }
auto-format = true
